'use client';

import { useState } from 'react';
import { toast } from 'sonner';
import { Loader2, Sparkles } from 'lucide-react';
import type { Field } from '@tax-form-layer/spec';
import { useEditor } from '@/lib/store';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';

const EXAMPLES = [
  'Right-aligned currency box for federal income tax withheld',
  'Employee SSN field formatted as XXX-XX-XXXX',
  'Checkbox for the retirement plan indicator',
];

export function AiFieldDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
}) {
  const addField = useEditor((s) => s.addField);
  const [prompt, setPrompt] = useState('');
  const [busy, setBusy] = useState(false);

  async function generate() {
    if (!prompt.trim()) return;
    setBusy(true);
    try {
      const { data } = useEditor.getState();
      const res = await fetch('/api/ai/generate-field', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, data }),
      });
      const json = (await res.json()) as { field?: Field; source?: string; error?: string };
      if (!res.ok || !json.field) throw new Error(json.error ?? 'Generation failed');
      addField(json.field);
      toast.success('Field added', {
        description: json.source === 'ai' ? 'Generated by AI' : 'Generated (offline heuristic)',
      });
      setPrompt('');
      onOpenChange(false);
    } catch (err) {
      toast.error('Could not generate field', {
        description: err instanceof Error ? err.message : undefined,
      });
    } finally {
      setBusy(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-4 w-4" /> Generate field with AI
          </DialogTitle>
          <DialogDescription>
            Describe the box in plain language. It is added to the current page for you to position.
          </DialogDescription>
        </DialogHeader>

        <Textarea
          rows={3}
          value={prompt}
          placeholder="e.g. Right-aligned currency box for Box 1 wages"
          onChange={(e) => setPrompt(e.target.value)}
        />
        <div className="flex flex-wrap gap-1.5">
          {EXAMPLES.map((ex) => (
            <button
              key={ex}
              className="rounded-full border bg-muted px-2 py-0.5 text-[10px] text-muted-foreground hover:bg-accent hover:text-accent-foreground"
              onClick={() => setPrompt(ex)}
            >
              {ex}
            </button>
          ))}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={busy}>
            Cancel
          </Button>
          <Button onClick={generate} disabled={busy || !prompt.trim()}>
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            Generate
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
